name: Frontend CI/CD

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  lint-and-test:
    name: Lint & Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install

      - name: Lint & Type Check
        run: |
          npm run lint
          npm run type-check

      - name: Run Jest tests
        run: |
          npm test -- --coverage

  deploy:
    name: Deploy to Vercel
    needs: lint-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --token=$VERCEL_TOKEN
